
export const ADD_USER_REQUEST = "ADD_USER_REQUEST";
export const ADD_USER_ERROR = "ADD_USER_ERROR";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const LOGOUT_USER_REQUEST = "LOGOUT_USER_REQUEST";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_ERROR = "LOGOUT_USER_ERROR";

export const ADD_POST_REQUEST = "ADD_POST_REQUEST";
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";
export const ADD_POST_ERROR = "ADD_POST_ERROR";


export const GET_POST_REQUEST = "GET_POST_REQUEST";
export const GET_POST_SUCCESS = "GET_POST_SUCCESS";
export const GET_POST_ERROR = "GET_POST_ERROR";
export const GET_SINGLE_POST_SUCCESS = "GET_SINGLE_POST_SUCCESS"


export const GET_USERS_REQUEST = "GET_USERS_REQUEST";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_ERROR = "GET_USERS_ERROR";

export const GIVE_LIKE = "GIVE_LIKE";
export const GET_LIKES = "GET_LIKES";
export const REMOVE_LIKES = "REMOVE_LIKES"

export const SAVE_POST = "SAVE_POST";
export const GET_SAVE_POST = "GET_SAVE_POST";
export const REMOVE_SAVE_POST = "REMOVE_SAVE_POST"

export const GET_PROFILE = "GET_PROFILE"; 

export const DELETE_POST = "DELETE_POST"; 


export const ADD_COMMENT = "ADD_COMMENT";
export const GET_COMMENT = "GET_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";



export const FOLLOW_REQUEST = "FOLLOW_REQUEST";
export const FOLLOW_SUCCESS = "FOLLOW_SUCCESS";
export const FOLLOW_ERROR = "FOLLOW_ERROR";
export const GET_FOLLOWER = "GET_FOLLOWER";
export const UN_FOLLOW = "UN_FOLLOW";